README.md: guessinggame.sh
	echo "# Guessing Game" > README.md
	echo "" >> README.md
	echo "Date : $$(date)" >> README.md
	echo "" >> README.md
	echo "Lignes de code dans guessinggame.sh : $$(wc -l < guessinggame.sh)" >> README.md
	echo "" >> README.md
